name: recipe_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  camera: ^0.10.5+4
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  http: ^0.13.6
  http_parser: ^4.0.2
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  shared_preferences: ^2.2.2
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  assets:
    - assets/images/
  uses-material-design: true
