platform :ios, '12.0'

target 'Runner' do
  use_frameworks!
  # Додайте ваші CocoaPods-залежності тут
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end